---
settings:
  name: Converged Systems Advisor
  rss_page: reference_new.html
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-tw,us-en,ja-jp,zh-cn,ko-kr
sidebar:
  entries:
  - title: 整合式系統顧問文件
    url: "/index.html"
  - title: 版本資訊
    entries:
    - title: 新增功能
      url: "/reference_new.html"
    - title: 新增功能歸檔
      url: "/reference_archive.html"
    - title: 已知問題
      url: "/reference_issues.html"
  - title: 概念
    entries:
    - title: 總覽
      url: "/concept_overview.html"
    - title: 架構
      url: "/concept_architecture.html"
    - title: 授權
      url: "/concept_licensing.html"
    - title: 安全性
      url: "/concept_security.html"
    - title: 使用者角色
      url: "/reference_user_roles.html"
  - title: 快速入門
    entries:
    - title: 快速入門
      url: "/task_quick_start.html"
    - title: 為環境做好準備
      url: "/task_prepare_environment.html"
    - title: 建立FlexPod 客戶帳戶以供使用
      url: "/task_create_accounts_flexpod_devices.html"
    - title: 設定及部署代理程式
      url: "/task_setup_deploy_agent.html"
    - title: 在入口網站中新增基礎架構
      url: "/task_add_infrastructure.html"
    - title: 設定通知
      url: "/task_configure_notifications.html"
    - title: 在代理程式上設定靜態IP
      url: "/task_setting_static_ip.html"
  - title: 監控基礎架構
    entries:
    - title: 檢閱您的基礎架構歷史記錄
      url: "/task_review_infrastructure_history.html"
    - title: 監控規則
      url: "/task_monitor_rules.html"
    - title: 產生報告
      url: "/task_generate_reports.html"
    - title: 追蹤支援合約
      url: "/task_track_contracts.html"
  - title: 驗證合作夥伴與經銷商的部署
    url: "/task_deployment_validation_partners_resellers.html"
  - title: 疑難排解
    url: "/task_troubleshooting.html"
  - title: 相關連結
    url: "/reference_additional_info.html"
  - title: 法律聲明
    url: "/reference_legal_notices.html"
